version: '3.1'

services:
  backend:
    build: .
    ports:
      - 8888:8888
  postgres:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /tmp/postgresql_data:/var/lib/postgresql/data
      - ./docker_compose_postgres_init.sql:/docker-entrypoint-initdb.d/docker_compose_postgres_init.sql
    ports:
      - 5432:5432
